import os
import pickle
import torch
from torch.utils.data import Dataset

MODEL_NAME = "distilbert-base-uncased"
DATA_DIR = "data"
OUTPUT_DIR = "models/ner_model"
ONNX_PATH = "models/ner_model.onnx"
MAX_LENGTH = 64
NUM_EPOCHS = 5
BATCH_SIZE = 16
LEARNING_RATE = 3e-5

def load_pickle(path):
    with open(path, "rb") as f:
        return pickle.load(f)
 
def load_all_data():
    train_data = load_pickle(os.path.join(DATA_DIR, "train_data.pkl"))
    val_data = load_pickle(os.path.join(DATA_DIR, "val_data.pkl"))
    test_data = load_pickle(os.path.join(DATA_DIR, "test_data.pkl"))
    label_config = load_pickle(os.path.join(DATA_DIR, "label_config.pkl"))
    return train_data, val_data, test_data, label_config

class NERDataset(Dataset):
    """Wraps the list of dictionaries generated by generate_ner_data.py into a PyTorch Dataset. 
    Since each item already contains input_ids, attention_mask, and labels from the BIO conversion step, 
    this class mainly serves as a simple wrapper that passes the data through to the model."""
 
    def __init__(self, data):
        self.data = data
 
    def __len__(self):
        return len(self.data)
 
    def __getitem__(self, idx):
        item = self.data[idx]
        return {
            "input_ids": torch.tensor(item["input_ids"], dtype=torch.long),
            "attention_mask": torch.tensor(item["attention_mask"], dtype=torch.long),
            "labels": torch.tensor(item["labels"], dtype=torch.long),
        }