import os
import pickle
import numpy as np
import torch
from torch.utils.data import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification,
)
from seqeval.metrics import classification_report, f1_score, precision_score, recall_score

MODEL_NAME = "distilbert-base-uncased"
DATA_DIR = "data"
OUTPUT_DIR = "models/ner_model"
ONNX_PATH = "models/ner_model.onnx"
MAX_LENGTH = 64
NUM_EPOCHS = 5
BATCH_SIZE = 16
LEARNING_RATE = 3e-5

def load_pickle(path):
    with open(path, "rb") as f:
        return pickle.load(f)
 
def load_all_data():
    train_data = load_pickle(os.path.join(DATA_DIR, "train_data.pkl"))
    val_data = load_pickle(os.path.join(DATA_DIR, "val_data.pkl"))
    test_data = load_pickle(os.path.join(DATA_DIR, "test_data.pkl"))
    label_config = load_pickle(os.path.join(DATA_DIR, "label_config.pkl"))
    return train_data, val_data, test_data, label_config

class NERDataset(Dataset):

    """Wraps the list of dictionaries generated by generate_ner_data.py into a PyTorch Dataset. 
    Since each item already contains input_ids, attention_mask, and labels from the BIO conversion step, 
    this class mainly serves as a simple wrapper that passes the data through to the model."""
 
    def __init__(self, data):
        self.data = data
 
    def __len__(self):
        return len(self.data)
 
    def __getitem__(self, idx):
        item = self.data[idx]
        return {
            "input_ids": torch.tensor(item["input_ids"], dtype=torch.long),
            "attention_mask": torch.tensor(item["attention_mask"], dtype=torch.long),
            "labels": torch.tensor(item["labels"], dtype=torch.long),
        }
    
def build_compute_metrics(id2label):
    def compute_metrics(eval_pred):
        predictions, labels = eval_pred
        predictions = np.argmax(predictions, axis=2)

        true_labels = []
        true_predictions = []
        
        for pred_seq, label_seq in zip(predictions, labels):
            seq_labels = []
            seq_preds = []
            for p, l in zip(pred_seq, label_seq):
                if l == -100:
                    continue
                seq_labels.append(id2label[l])
                seq_preds.append(id2label[p])
            true_labels.append(seq_labels)
            true_predictions.append(seq_preds)
 
        return {
            "precision": precision_score(true_labels, true_predictions),
            "recall": recall_score(true_labels, true_predictions),
            "f1": f1_score(true_labels, true_predictions),
        }
 
    return compute_metrics

def fix_padding_labels(data):
    fixed = []
    for item in data:
        labels = list(item["labels"])
        mask = item["attention_mask"]
        for i, m in enumerate(mask):
            if m == 0:
                labels[i] = -100
        fixed.append({
            "input_ids": item["input_ids"],
            "attention_mask": item["attention_mask"],
            "labels": labels,
        })
    return fixed

CUSTOM_TEST_SENTENCES = [
    "Please send this to Aditya at 12 Main Street, Khurja.",
    "Contact Priya Nair for more details.",
    "I live near the old bus stand in Meerut.",
    "The weather today is really pleasant.",
    "Ravi Kumar will be visiting our Pune office next week.",
]
 
def run_custom_inference(model, tokenizer, id2label, sentences, device):
    model.eval()
    for sentence in sentences:
        encoding = tokenizer(
            sentence,
            return_offsets_mapping=True,
            truncation=True,
            max_length=MAX_LENGTH,
            padding="max_length",
            return_tensors="pt",
        )
        offsets = encoding.pop("offset_mapping")[0]
        encoding = {k: v.to(device) for k, v in encoding.items()}
 
        with torch.no_grad():
            outputs = model(**encoding)
        preds = torch.argmax(outputs.logits, dim=2)[0].cpu().numpy()
 
        tokens = tokenizer.convert_ids_to_tokens(encoding["input_ids"][0].cpu().numpy())
        print(f"\n{sentence}")
        for tok, pred_id, (start, end) in zip(tokens, preds, offsets):
            if start == end:
                continue
            label = id2label[pred_id]
            if label != "O":
                print(f"  {tok:15s} -> {label}")

def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
 
    os.makedirs("models", exist_ok=True)
 
    train_data, val_data, test_data, label_config = load_all_data()
    label_list = label_config["label_list"]
    label2id = label_config["label2id"]
    id2label = label_config["id2label"]
    num_labels = len(label_list)
    print(f"Loaded {len(train_data)} train / {len(val_data)} val / {len(test_data)} test examples")
    print(f"Labels: {label_list}")
 
    train_data = fix_padding_labels(train_data)
    val_data = fix_padding_labels(val_data)
    test_data = fix_padding_labels(test_data)
 
    train_dataset = NERDataset(train_data)
    val_dataset = NERDataset(val_data)
    test_dataset = NERDataset(test_data)
 
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForTokenClassification.from_pretrained(
        MODEL_NAME,
        num_labels=num_labels,
        id2label=id2label,
        label2id=label2id,
    ).to(device)
 
    data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)
 
    training_args = TrainingArguments(
        output_dir=OUTPUT_DIR,
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=LEARNING_RATE,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=NUM_EPOCHS,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        greater_is_better=True,
        logging_steps=50,
        report_to="none",
    )
 
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=data_collator,
        compute_metrics=build_compute_metrics(id2label),
    )
 
    print("\n--- Training ---")
    trainer.train()
 
    print("\n--- Validation results (best checkpoint) ---")
    val_metrics = trainer.evaluate(val_dataset)
    print(val_metrics)
 
    print("\n--- Test set results ---")
    test_metrics = trainer.evaluate(test_dataset)
    print(test_metrics)
 
    predictions, labels, _ = trainer.predict(test_dataset)
    preds = np.argmax(predictions, axis=2)
    true_labels, true_preds = [], []
    for pred_seq, label_seq in zip(preds, labels):
        seq_labels, seq_preds = [], []
        for p, l in zip(pred_seq, label_seq):
            if l == -100:
                continue
            seq_labels.append(id2label[l])
            seq_preds.append(id2label[p])
        true_labels.append(seq_labels)
        true_preds.append(seq_preds)
    print("\n--- Per-entity classification report ---")
    print(classification_report(true_labels, true_preds))
 
    trainer.save_model(OUTPUT_DIR)     # saving the final PyTorch model + tokenizer
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"\nSaved model + tokenizer to {OUTPUT_DIR}")
 
    print("\n--- Custom sentence sanity check ---")       # sanity check on hand-written sentences, not from synthetic data
    run_custom_inference(model, tokenizer, id2label, CUSTOM_TEST_SENTENCES, device)
 
    print("\n--- Exporting to ONNX ---")     # Export to ONNX for fast local inference in the actual app
    model.eval()
    model.to("cpu")
    dummy_input = tokenizer(
        "This is a dummy sentence for export.",
        return_tensors="pt",
        padding="max_length",
        truncation=True,
        max_length=MAX_LENGTH,
    )
 
    torch.onnx.export(
        model,
        (dummy_input["input_ids"], dummy_input["attention_mask"]),
        ONNX_PATH,
        input_names=["input_ids", "attention_mask"],
        output_names=["logits"],
        dynamic_axes={
            "input_ids": {0: "batch_size"},
            "attention_mask": {0: "batch_size"},
            "logits": {0: "batch_size"},
        },
        opset_version=14,
        dynamo=False,
    )
    print(f"Saved ONNX model to {ONNX_PATH}")
 
    import onnxruntime as ort     #checking onxx output is matching with pytorch output
    session = ort.InferenceSession(ONNX_PATH)
    onnx_inputs = {
        "input_ids": dummy_input["input_ids"].numpy(),
        "attention_mask": dummy_input["attention_mask"].numpy(),
    }
    onnx_logits = session.run(None, onnx_inputs)[0]
    with torch.no_grad():
        torch_logits = model(**dummy_input).logits.numpy()
 
    max_diff = np.abs(onnx_logits - torch_logits).max()
    print(f"Max difference between PyTorch and ONNX outputs: {max_diff:.6f}")
    if max_diff < 1e-3:
        print("ONNX export verified: outputs match.")
    else:
        print("WARNING: ONNX output differs from PyTorch output more than expected — investigate before using in the app.")
 

if __name__ == "__main__":
    main()