import os
import pickle
import numpy as np
import torch
from torch.utils.data import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification,
)
from seqeval.metrics import classification_report, f1_score, precision_score, recall_score

MODEL_NAME = "distilbert-base-uncased"
DATA_DIR = "data"
OUTPUT_DIR = "models/ner_model"
ONNX_PATH = "models/ner_model.onnx"
MAX_LENGTH = 64
NUM_EPOCHS = 5
BATCH_SIZE = 16
LEARNING_RATE = 3e-5

def load_pickle(path):
    with open(path, "rb") as f:
        return pickle.load(f)
 
def load_all_data():
    train_data = load_pickle(os.path.join(DATA_DIR, "train_data.pkl"))
    val_data = load_pickle(os.path.join(DATA_DIR, "val_data.pkl"))
    test_data = load_pickle(os.path.join(DATA_DIR, "test_data.pkl"))
    label_config = load_pickle(os.path.join(DATA_DIR, "label_config.pkl"))
    return train_data, val_data, test_data, label_config

class NERDataset(Dataset):
    """Wraps the list of dictionaries generated by generate_ner_data.py into a PyTorch Dataset. 
    Since each item already contains input_ids, attention_mask, and labels from the BIO conversion step, 
    this class mainly serves as a simple wrapper that passes the data through to the model."""
 
    def __init__(self, data):
        self.data = data
 
    def __len__(self):
        return len(self.data)
 
    def __getitem__(self, idx):
        item = self.data[idx]
        return {
            "input_ids": torch.tensor(item["input_ids"], dtype=torch.long),
            "attention_mask": torch.tensor(item["attention_mask"], dtype=torch.long),
            "labels": torch.tensor(item["labels"], dtype=torch.long),
        }
    
def build_compute_metrics(id2label):
    def compute_metrics(eval_pred):
        predictions, labels = eval_pred
        predictions = np.argmax(predictions, axis=2)

        true_labels = []
        true_predictions = []
        
        for pred_seq, label_seq in zip(predictions, labels):
            seq_labels = []
            seq_preds = []
            for p, l in zip(pred_seq, label_seq):
                if l == -100:
                    continue
                seq_labels.append(id2label[l])
                seq_preds.append(id2label[p])
            true_labels.append(seq_labels)
            true_predictions.append(seq_preds)
 
        return {
            "precision": precision_score(true_labels, true_predictions),
            "recall": recall_score(true_labels, true_predictions),
            "f1": f1_score(true_labels, true_predictions),
        }
 
    return compute_metrics